# =============================================================================
# ArgoCD ConfigMap - cấu hình chung cho ArgoCD
# =============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Git repositories
  repositories: |
    - url: https://github.com/<ORG>/tiktok-gitops.git
      type: git

  # Resource health checks
  resource.customizations.health.argoproj.io_Application: |
    hs = {}
    hs.status = "Progressing"
    hs.message = ""
    if obj.status ~= nil then
      if obj.status.health ~= nil then
        hs.status = obj.status.health.status
        if obj.status.health.message ~= nil then
          hs.message = obj.status.health.message
        end
      end
    end
    return hs

  # Webhook configuration
  webhook.github.secret: $webhook-github-secret

  # Application controller settings
  timeout.reconciliation: 180s
